### ISSUE TITLE
logistic_regression

### ISSUE THREAD

**Issue by walter-weinmann** [saimadhu-polamuri/DataAspirant_codes#1]
Running the module gives:

```
C:\ProgramData\Anaconda3\python.exe "D:/Walter Study/Udacity/Deep Learning/SoftwarePractice/Logistic_Binary_Classification/logistic_regression.py"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.

Traceback (most recent call last):
  File "D:/Walter Study/Udacity/Deep Learning/SoftwarePractice/Logistic_Binary_Classification/logistic_regression.py", line 194, in <module>
    main()
  File "D:/Walter Study/Udacity/Deep Learning/SoftwarePractice/Logistic_Binary_Classification/logistic_regression.py", line 176, in main
    feature_target_histogram(feature_target_frequencies, feature)
  File "D:/Walter Study/Udacity/Deep Learning/SoftwarePractice/Logistic_Binary_Classification/logistic_regression.py", line 112, in feature_target_histogram
    py.image.save_as(fig, filename=feature_header + '_Target_Histogram.png')
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\plotly\plotly.py", line 831, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\plotly\plotly.py", line 744, in get
    response = v2.images.create(payload)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\api\v2\images.py", line 18, in create
    return request('post', url, json=body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\api\v2\utils.py", line 139, in request
    cls=utils.PlotlyJSONEncoder)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\utils.py", line 136, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\plotly\utils.py", line 204, in default
    return _json.JSONEncoder.default(self, obj)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'dict_keys' is not JSON serializable
```

**Comment by DanielLSM** [comment]
check my pull request
